// generate-config.js
// Reads .env and writes Frontend/js/config.js (gitignored)

const fs = require('fs');
const path = require('path');

// Read .env
const envPath = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
  console.error('❌ No .env file found. Copy .envexample to .env and fill in your keys.');
  process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
  const match = line.match(/^\s*([\w]+)\s*=\s*["']?(.+?)["']?\s*$/);
  if (match) env[match[1]] = match[2];
});

const url = env.SUPABASE_URL;
const key = env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('❌ .env must have SUPABASE_URL and SUPABASE_ANON_KEY');
  process.exit(1);
}

// Write env.js (for frontend)
const envContent = `// AUTO-GENERATED by generate-config.js — do not edit manually
window.__SUPABASE_URL = '${url}';
window.__SUPABASE_ANON_KEY = '${key}';
`;

const outPath = path.join(__dirname, '..', 'Frontend', 'js', 'env.js');
fs.writeFileSync(outPath, envContent);
console.log('✅ Frontend/js/env.js generated from .env');
